model:
  embedding_dim: 512
  img_size: 128
  hidden_dims: [512, 256, 128, 64, 32]

training:
  num_epochs: 20
  batch_size: 64
  learning_rate: 0.0001  # 1e-4 in decimal notation for YAML compatibility
  weight_decay: 0.00001  # 1e-5 in decimal notation

data:
  train_size: 162000
  val_size: 20000
  num_workers: 0  # Set to 0 to avoid multiprocessing issues on VMs
